# Etapa de construcción
FROM node:16-alpine as build

WORKDIR /app

# Instalar dependencias
COPY frontend/package*.json ./
RUN npm install

# Copiar código fuente
COPY frontend/ .

# Construir la aplicación
RUN npm run build

# Etapa de producción
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]