FROM python:3.10.11-slim

WORKDIR /app

# Evitar que Python genere archivos .pyc
ENV PYTHONDONTWRITEBYTECODE 1
# Evitar que Python almacene en búfer la salida
ENV PYTHONUNBUFFERED 1

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el proyecto
COPY backend/ .

# Puerto que expondrá el contenedor
EXPOSE 8000

# Comando para ejecutar al iniciar el contenedor
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]