# Generated by Django 5.2 on 2025-05-06 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(db_column='categoria_id', primary_key=True, serialize=False, verbose_name='ID de Categoría')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('distribuidora_id', models.AutoField(db_column='distribuidora_id', primary_key=True, serialize=False, verbose_name='ID de Distribuidora')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('nit', models.CharField(max_length=50, verbose_name='NIT')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=8, verbose_name='Teléfono')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL del Logo')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Distribuidora',
                'verbose_name_plural': 'Distribuidoras',
                'db_table': 'distribuidora',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marca_id', models.AutoField(db_column='marca_id', primary_key=True, serialize=False, verbose_name='ID de Marca')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Marca')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL del Logo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(db_column='producto_id', primary_key=True, serialize=False, verbose_name='ID de Producto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('peso', models.CharField(max_length=50, verbose_name='Peso/Volumen')),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de la Imagen')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.categoria')),
                ('distribuidora', models.ForeignKey(db_column='distribuidora_id', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.distribuidora')),
                ('marca', models.ForeignKey(db_column='marca_id', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('inventario_id', models.AutoField(db_column='inventario_id', primary_key=True, serialize=False, verbose_name='ID de Inventario')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(default=0, verbose_name='Stock Mínimo')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('producto', models.OneToOneField(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
            },
        ),
    ]
