# Generated by Django 5.2 on 2025-04-07 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(db_column='persona_id', primary_key=True, serialize=False, verbose_name='ID de Persona')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=255, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido Materno')),
                ('telefono', models.CharField(max_length=8, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Carnet de Identidad')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(db_column='rol_id', primary_key=True, serialize=False, verbose_name='ID del Rol')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del Rol')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción del Rol')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usuario_id', models.AutoField(db_column='usuario_id', primary_key=True, serialize=False, verbose_name='ID de Usuario')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Nombre de Usuario')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('ultimo_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Es Superusuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='usuarios.persona', verbose_name='Persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='SistemaLog',
            fields=[
                ('log_id', models.AutoField(db_column='log_id', primary_key=True, serialize=False, verbose_name='ID de Log')),
                ('accion', models.CharField(max_length=255, verbose_name='Acción Realizada')),
                ('tabla', models.CharField(max_length=100, verbose_name='Tabla Afectada')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log del Sistema',
                'verbose_name_plural': 'Logs del Sistema',
                'db_table': 'sistema_logs',
            },
        ),
    ]
